project:
  type: website

website:
  title: "MiR Blog"
  navbar:
    right:
      - about.qmd
      
      # - text: 'MiR Community'
      # - file: index.qmd
      
      
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css



